name: Lint JavaScript

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: ESLint (JS/TS) Action
        run: npx eslint "*.js"

      - name: Tests
        run: |
          npm test --coverage --json >> readme.md  # Exécute les tests et génère un fichier de résultats au format JSON
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update test results in README"
          git push
