name: Lint JavaScript

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: ESLint (JS/TS) Action
        run: npx eslint "*.js"

      - name: Tests
        run: |
          TEST_OUTPUT=$(npm test --coverage)  # Exécute les tests et récupère la sortie
          echo "TEST_OUTPUT=$TEST_OUTPUT" >> $GITHUB_ENV  # Enregistre la sortie dans une variable d'environnement

      # Étape 5 : Extraire les résultats des tests et mettre à jour README.md
      - name: Update README with test results
        run: |
          # Extraire la couverture des tests de la sortie de Vitest
          COVERAGE=$(echo "$TEST_OUTPUT" | grep -oP 'All files covered: \K[0-9.]+')

          # Si on trouve un pourcentage de couverture, on met à jour le README
          if [[ -n "$COVERAGE" ]]; then
            sed -i "s|## Test Results|## Test Results\n\nTest Coverage: $COVERAGE%" README.md
          else
            echo "Pas de couverture de test trouvée."
          fi

      # Étape 6 : Committer et pousser les modifications sur le README.md
      - name: Commit and push updated README
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update test results in README"
          git push
