name: Lint JavaScript

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: ESLint (JS/TS) Action
        run: npx eslint "*.js"

      - name: Tests
        run: |
          npm test --coverage --json > result.json  # Exécute les tests et génère un fichier de résultats au format JSON

      - name: Update README with test results
        run: |
          # Extraire les résultats des tests depuis le fichier JSON
          TEST_RESULTS=$(cat result.json | jq '.coverageMap')

          # Insérer ou mettre à jour les résultats dans la section "Test Results" du README
          sed -i "/## Test Results/a\\
          $TEST_RESULTS" README.md

      # Étape 6 : Committer et pousser les modifications sur le README.md
      - name: Commit and push updated README
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update test results in README"
          git push
