name: Lint JavaScript

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: ESLint (JS/TS) Action
        run: npx eslint "*.js"

      - name: Tests
        run: |
          npm test --coverage --reporter json > result.json  # Exécute les tests et génère un fichier de résultats au format JSON

      # Étape 5 : Mettre à jour le README avec les résultats des tests
      - name: Update README with test results
        run: |
          # Extraire les résultats du fichier result.json
          TEST_RESULT=$(jq '.total.coverage' result.json)  # Ajuste en fonction de la structure du JSON généré par Vitest

          # Remplacer la section "Test Results" dans README.md
          sed -i "s|## Test Results|## Test Results\n\nTest Coverage: $TEST_RESULT%" README.md

      # Étape 6 : Committer et pousser les modifications sur le README.md
      - name: Commit and push updated README
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update test results in README"
          git push
